### ISSUE TITLE
ROBOFLOW_API_KEY ?

### ISSUE THREAD

**Issue by yghcats** [roboflow-ai/zero-shot-object-tracking#4]
Hi,
  python clip_object_tracker.py --source data/video/fish.mp4 --url https://detect.roboflow.com/playing-fish-ow27d/1 --api_key ROBOFLOW_API_KEY
  ROBOFLOW_API_KEY：Where did you get it?
  
  Thank you.

**Comment by Jacobsolawetz** [comment]
Hello @yghcats - you can get your API Key from your Roboflow account after training a model in the Roboflow application.

We have also added support for YOLOv5 and soon YOLOv4, if you want to train your model outside of Roboflow.

**Comment by yeldarby** [comment]
There's a walkthrough of getting your API key here; you'll need a (free) [Roboflow](https://roboflow.com) account: https://docs.roboflow.com/rest-api
