### ISSUE TITLE
a Question not an issuses 

### ISSUE THREAD

**Issue by totoadel** [roboflow-ai/zero-shot-object-tracking#6]
How can i apply this with YoloR Model

**Comment by yeldarby** [comment]
We're working on adding YOLOv4 support next, but PRs welcome to add support for other models!

Here was the PR which added YOLOv5 support that you can use as a template: https://github.com/roboflow-ai/zero-shot-object-tracking/pull/5

**Comment by Jacobsolawetz** [comment]
Yes @totoadel - the YOLOv5 PR will be a good template to work from, as most of the YOLOR repo, including the inference routines were forked from YOLOv5.

It would also be nice to know that your PR can implement YOLOR inference with a custom model, trained from a tutorial like this one https://blog.roboflow.com/train-yolor-on-a-custom-dataset/

Best of luck and keep us posted in this thread

**Comment by totoadel** [comment]
thank you @Jacobsolawetz  , i already  use [](https://blog.roboflow.com/train-yolor-on-a-custom-dataset/) to train my datasets, but i test this ropo with my yolor model but it didn't work

**Comment by totoadel** [comment]
@Jacobsolawetz  @yeldarby Do you prefer YoloR or Yolov5?

**Comment by Jacobsolawetz** [comment]
@totoadel Despite the COCO evaluations, I have seen superior custom training speed and results from YOLOv5 and recommend you use it.

**Comment by totoadel** [comment]
@Jacobsolawetz  Thank you so much< i will use yolov5 in my work>
