### ISSUE TITLE
How to draw a tracing line?

### ISSUE THREAD

**Issue by totoadel** [roboflow-ai/zero-shot-object-tracking#8]
hi @Jacobsolawetz and @maxhs2014 
i want to draw a tracing line for the object , how i can i do that?

**Comment by Jacobsolawetz** [comment]
Hello @totoadel we don’t currently have that visualization but it would be cool to add it. Do you have an example video of what you’re looking for? And how many frames back does the tracing line follow?

**Comment by totoadel** [comment]
yes like what happened here in this video.
[](https://www.youtube.com/watch?v=Cu3ERM0Zk4s)
and all frames the object are still founded.

**Comment by Jacobsolawetz** [comment]
Ok cool - thanks for the example, we will put it on the list of todo

If you want to try a PR, it would be maintaining a dictionary for each object with history of box center locations, then plotting that line at visualization time

**Comment by totoadel** [comment]
than you very much @Jacobsolawetz

**Comment by totoadel** [comment]
> 
> 
> Ok cool - thanks for the example, we will put it on the list of todo
> 
> If you want to try a PR, it would be maintaining a dictionary for each object with history of box center locations, then plotting that line at visualization time

i did it thank you very much.
this is the code


```
height, width, _ = im0.shape
                        x1, y1, x2, y2 = max(0, int(bboxes[0])), max(0, int(bboxes[1])), min(width,
                                                                                             int(bboxes[2])), min(
                            height, int(bboxes[3]))
                        center = (int((x1 + x2) / 2), int((y1 + y2) / 2))
                        chk = checkKey_track(id_track, (id))
                        if chk == 1:
                            resl=all_values(id_track, id)
                            for key in list (resl):
                                cv2.circle(im0, resl[key], radius=5, color=color, thickness=-1)
                                upd_dict = {(count_id): center}
                                id_track[(id)].update(upd_dict)
                            #resl.clear()
                        else:
                            upd_dict = {(count_id): center}
                            id_track[(id)]=(upd_dict)
```



```
def checkKey_track(dict, key):
    if key in dict.keys():
        return 1
    else:
        return 0


def all_values(dict_obj,ids):
 for p_id, p_info in dict_obj.items():
    if ids == p_id:
        for key in p_info:
            p_info[key]
 return p_info
```

**Comment by yeldarby** [comment]
Nice! Can you post an example video?

**Comment by Jacobsolawetz** [comment]
@maxhs2014, let's take a look this week together

**Comment by totoadel** [comment]
let me upload video to you tube

**Comment by totoadel** [comment]
https://youtu.be/HlvybeSzbqs 
I'm very happy, because I'm a Java developer, not Python,

**Comment by XiangqingZhang** [comment]
> > Ok cool - thanks for the example, we will put it on the list of todo
> > If you want to try a PR, it would be maintaining a dictionary for each object with history of box center locations, then plotting that line at visualization time
> 
> i did it thank you very much. @Jacobsolawetz this is the code
> 
> ```
> height, width, _ = im0.shape
>                         x1, y1, x2, y2 = max(0, int(bboxes[0])), max(0, int(bboxes[1])), min(width,
>                                                                                              int(bboxes[2])), min(
>  height, int(bboxes[3]))
>  center = (int((x1 + x2) / 2), int((y1 + y2) / 2))
>  chk = checkKey_track(id_track, (id))
>   if chk == 1:
>             resl=all_values(id_track, id)
>             for key in list (resl):
>                         cv2.circle(im0, resl[key], radius=5, color=color, thickness=-1)
>                          upd_dict = {(count_id): center}
>                          id_track[(id)].update(upd_dict)
>  else:
>            upd_dict = {(count_id): center}
>             id_track[(id)]=(upd_dict)
> ```
> 
> ```
> def checkKey_track(dict, key):
>     if key in dict.keys():
>         return 1
>     else:
>         return 0
> 
> 
> def all_values(dict_obj,ids):
>  for p_id, p_info in dict_obj.items():
>     if ids == p_id:
>         for key in p_info:
>             p_info[key]
>  return p_info
> ```

Which file to add these codes?

**Comment by totoadel** [comment]
> > > Ok cool - thanks for the example, we will put it on the list of todo
> > > If you want to try a PR, it would be maintaining a dictionary for each object with history of box center locations, then plotting that line at visualization time
> > 
> > 
> > i did it thank you very much. @Jacobsolawetz this is the code
> > ```
> > height, width, _ = im0.shape
> >                         x1, y1, x2, y2 = max(0, int(bboxes[0])), max(0, int(bboxes[1])), min(width,
> >                                                                                              int(bboxes[2])), min(
> >  height, int(bboxes[3]))
> >  center = (int((x1 + x2) / 2), int((y1 + y2) / 2))
> >  chk = checkKey_track(id_track, (id))
> >   if chk == 1:
> >             resl=all_values(id_track, id)
> >             for key in list (resl):
> >                         cv2.circle(im0, resl[key], radius=5, color=color, thickness=-1)
> >                          upd_dict = {(count_id): center}
> >                          id_track[(id)].update(upd_dict)
> >  else:
> >            upd_dict = {(count_id): center}
> >             id_track[(id)]=(upd_dict)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > def checkKey_track(dict, key):
> >     if key in dict.keys():
> >         return 1
> >     else:
> >         return 0
> > 
> > 
> > def all_values(dict_obj,ids):
> >  for p_id, p_info in dict_obj.items():
> >     if ids == p_id:
> >         for key in p_info:
> >             p_info[key]
> >  return p_info
> > ```
> 
> Which file to add these codes?

Detect.py

**Comment by XiangqingZhang** [comment]
I can't find detect.py, can you help me in detail? thank you


> > > > Ok cool - thanks for the example, we will put it on the list of todo
> > > > If you want to try a PR, it would be maintaining a dictionary for each object with history of box center locations, then plotting that line at visualization time
> > > 
> > > 
> > > i did it thank you very much. @Jacobsolawetz this is the code
> > > ```
> > > height, width, _ = im0.shape
> > >                         x1, y1, x2, y2 = max(0, int(bboxes[0])), max(0, int(bboxes[1])), min(width,
> > >                                                                                              int(bboxes[2])), min(
> > >  height, int(bboxes[3]))
> > >  center = (int((x1 + x2) / 2), int((y1 + y2) / 2))
> > >  chk = checkKey_track(id_track, (id))
> > >   if chk == 1:
> > >             resl=all_values(id_track, id)
> > >             for key in list (resl):
> > >                         cv2.circle(im0, resl[key], radius=5, color=color, thickness=-1)
> > >                          upd_dict = {(count_id): center}
> > >                          id_track[(id)].update(upd_dict)
> > >  else:
> > >            upd_dict = {(count_id): center}
> > >             id_track[(id)]=(upd_dict)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > def checkKey_track(dict, key):
> > >     if key in dict.keys():
> > >         return 1
> > >     else:
> > >         return 0
> > > 
> > > 
> > > def all_values(dict_obj,ids):
> > >  for p_id, p_info in dict_obj.items():
> > >     if ids == p_id:
> > >         for key in p_info:
> > >             p_info[key]
> > >  return p_info
> > > ```
> > 
> > 
> > Which file to add these codes?
> 
> Detect.py
